'use strict'

const Docker = require('dockerode')
const fs = require('fs')
const path = require('path')

const CONFIG_DIR = path.join(__dirname, 'data')
const CONTAINER_CONFIG_PATH = '/app/translator-config.toml'

// ─── Default configuration ──────────────────────────────────────────────────
// Values match the translator_sv2 Rust defaults and the SRI docker-compose setup.

// Defaults sourced from translator_sv2/config-examples/mainnet/tproxy-config-hosted-pool-example.toml
const DEFAULTS = Object.freeze({
  deployment: {
    image: 'stratumv2/translator_sv2',
    imageTag: 'main',
    containerName: 'tproxy_sv2',
    restartPolicy: 'unless-stopped',
    hostDownstreamPort: 34255,
    hostMonitoringPort: 9092,
    pullPolicy: 'ifNotPresent'
  },
  translator: {
    downstreamAddress: '0.0.0.0',
    downstreamPort: 34255,
    maxSupportedVersion: 2,
    minSupportedVersion: 2,
    downstreamExtranonce2Size: 4,
    userIdentity: 'plebhash',
    aggregateChannels: true,
    supportedExtensions: [],
    requiredExtensions: [],
    monitoringAddress: '0.0.0.0:9092',
    downstreamDifficultyConfig: {
      minIndividualMinerHashrate: 100_000.0,
      sharesPerMinute: 6.0,
      enableVardiff: true,
      jobKeepaliveIntervalSecs: 60
    },
    upstreams: [
      {
        address: '75.119.150.111',
        port: 3333,
        authorityPubkey: '9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72'
      },
      {
        address: '107.170.42.64',
        port: 3333,
        authorityPubkey: '9awtMD5KQgvRUh2yFbjVeT7b6hjipWcAsQHd6wEhgtDT9soosna'
      }
    ]
  }
})

// ─── Helpers ────────────────────────────────────────────────────────────────

function deepMerge (target, source) {
  const result = { ...target }
  for (const key of Object.keys(source)) {
    if (source[key] === undefined || source[key] === null) continue
    if (
      typeof source[key] === 'object' &&
      !Array.isArray(source[key]) &&
      target[key] &&
      typeof target[key] === 'object' &&
      !Array.isArray(target[key])
    ) {
      result[key] = deepMerge(target[key], source[key])
    } else {
      result[key] = source[key]
    }
  }
  return result
}

function tomlFloat (v) {
  const s = String(v)
  return s.includes('.') ? s : s + '.0'
}

function generateToml (c) {
  const lines = [
    '# Generated by sv2-translator-proxy',
    '',
    `downstream_address = "${c.downstreamAddress}"`,
    `downstream_port = ${c.downstreamPort}`,
    '',
    `max_supported_version = ${c.maxSupportedVersion}`,
    `min_supported_version = ${c.minSupportedVersion}`,
    '',
    `downstream_extranonce2_size = ${c.downstreamExtranonce2Size}`,
    '',
    `user_identity = "${c.userIdentity}"`,
    '',
    `aggregate_channels = ${c.aggregateChannels}`,
    '',
    `supported_extensions = [${c.supportedExtensions.join(', ')}]`,
    `required_extensions = [${c.requiredExtensions.join(', ')}]`
  ]
  if (c.monitoringAddress) {
    lines.push('', `monitoring_address = "${c.monitoringAddress}"`)
  }
  const d = c.downstreamDifficultyConfig
  lines.push(
    '',
    '[downstream_difficulty_config]',
    `min_individual_miner_hashrate = ${tomlFloat(d.minIndividualMinerHashrate)}`,
    `shares_per_minute = ${tomlFloat(d.sharesPerMinute)}`,
    `enable_vardiff = ${d.enableVardiff}`,
    `job_keepalive_interval_secs = ${d.jobKeepaliveIntervalSecs}`
  )
  for (const u of c.upstreams) {
    lines.push(
      '',
      '[[upstreams]]',
      `address = "${u.address}"`,
      `port = ${u.port}`,
      `authority_pubkey = "${u.authorityPubkey}"`
    )
  }
  return lines.join('\n') + '\n'
}

function parseMonitoringPort (addr) {
  if (!addr) return null
  const parts = addr.split(':')
  if (parts.length === 2) {
    const p = parseInt(parts[1], 10)
    if (!isNaN(p) && p > 0 && p <= 65535) return p
  }
  return null
}

function validate (config) {
  const errs = []
  const { deployment: dep, translator: t } = config

  if (!dep.image) errs.push('deployment.image is required')
  if (!dep.imageTag) errs.push('deployment.imageTag is required')
  if (!dep.containerName) errs.push('deployment.containerName is required')

  if (!['no', 'always', 'unless-stopped', 'on-failure'].includes(dep.restartPolicy)) {
    errs.push('deployment.restartPolicy invalid')
  }
  if (!['ifNotPresent', 'always', 'never'].includes(dep.pullPolicy)) {
    errs.push('deployment.pullPolicy invalid')
  }

  for (const field of ['hostDownstreamPort', 'hostMonitoringPort']) {
    if (dep[field] < 1 || dep[field] > 65535) errs.push(`deployment.${field} out of range`)
  }

  if (!t.downstreamAddress) errs.push('translator.downstreamAddress is required')
  if (t.downstreamPort < 1 || t.downstreamPort > 65535) errs.push('translator.downstreamPort out of range')
  if (!t.userIdentity) errs.push('translator.userIdentity is required')

  if (!Array.isArray(t.upstreams) || t.upstreams.length === 0) {
    errs.push('translator.upstreams must be a non-empty array')
  } else {
    t.upstreams.forEach((u, i) => {
      if (!u.address) errs.push(`upstreams[${i}].address required`)
      if (u.port < 1 || u.port > 65535) errs.push(`upstreams[${i}].port out of range`)
      if (!u.authorityPubkey) errs.push(`upstreams[${i}].authorityPubkey required`)
    })
  }

  const d = t.downstreamDifficultyConfig
  if (!d) {
    errs.push('translator.downstreamDifficultyConfig is required')
  } else {
    if (d.minIndividualMinerHashrate <= 0) errs.push('minIndividualMinerHashrate must be positive')
    if (d.sharesPerMinute <= 0) errs.push('sharesPerMinute must be positive')
    if (d.jobKeepaliveIntervalSecs < 0) errs.push('jobKeepaliveIntervalSecs must be >= 0')
  }

  return errs
}

function demuxStream (buf) {
  const out = { stdout: '', stderr: '' }
  let off = 0
  while (off < buf.length) {
    if (off + 8 > buf.length) { out.stdout += buf.slice(off).toString('utf8'); break }
    const type = buf.readUInt8(off)
    const size = buf.readUInt32BE(off + 4)
    off += 8
    if (off + size > buf.length) { out.stdout += buf.slice(off).toString('utf8'); break }
    const payload = buf.slice(off, off + size).toString('utf8')
    if (type === 1) out.stdout += payload
    else if (type === 2) out.stderr += payload
    off += size
  }
  return out
}

// ─── Service ────────────────────────────────────────────────────────────────

class TranslatorSv2Service {
  constructor (opts = {}) {
    const socketPath = opts.dockerSocket || process.env.DOCKER_HOST || undefined
    this.docker = new Docker(socketPath ? { socketPath } : undefined)
    this.configDir = opts.configDir || CONFIG_DIR
    this.configFile = path.join(this.configDir, 'config.json')
    this.tomlFile = path.join(this.configDir, 'translator-config.toml')
  }

  /**
   * Wrap Docker API calls with a clear error if the daemon is unreachable.
   */
  async _dockerCall (fn) {
    try {
      return await fn()
    } catch (err) {
      if (err.code === 'ENOENT' || err.code === 'ECONNREFUSED') {
        throw new Error('Docker is not running. Start Docker Desktop and try again.')
      }
      throw err
    }
  }

  _ensureDir () { fs.mkdirSync(this.configDir, { recursive: true }) }

  getDefaults () { return JSON.parse(JSON.stringify(DEFAULTS)) }

  loadConfig () {
    const defaults = this.getDefaults()
    try {
      return deepMerge(defaults, JSON.parse(fs.readFileSync(this.configFile, 'utf8')))
    } catch { return defaults }
  }

  saveConfig (partial) {
    this._ensureDir()
    const merged = deepMerge(this.getDefaults(), partial)
    fs.writeFileSync(this.configFile, JSON.stringify(merged, null, 2))
    return merged
  }

  _writeToml (translatorCfg) {
    this._ensureDir()
    const toml = generateToml(translatorCfg)
    fs.writeFileSync(this.tomlFile, toml)
    return this.tomlFile
  }

  async _pull (image) {
    return new Promise((resolve, reject) => {
      this.docker.pull(image, (err, stream) => {
        if (err) return reject(err)
        this.docker.modem.followProgress(stream, (e, o) => e ? reject(e) : resolve(o))
      })
    })
  }

  async _imageExists (image) {
    try {
      await this.docker.getImage(image).inspect()
      return true
    } catch (err) {
      if (err.statusCode === 404) return false
      throw err
    }
  }

  async _findContainer (name) {
    try {
      const c = this.docker.getContainer(name)
      await c.inspect()
      return c
    } catch (err) {
      if (err.statusCode === 404) return null
      throw err
    }
  }

  async getStatus () {
    const config = this.loadConfig()
    const name = config.deployment.containerName
    const notFound = { status: 'not_found', running: false, containerId: null, containerName: name, image: null, startedAt: null, finishedAt: null, restartCount: 0, ports: null, config }
    try {
      const info = await this.docker.getContainer(name).inspect()
      return {
        status: info.State.Status,
        running: info.State.Running,
        containerId: info.Id,
        containerName: name,
        image: info.Config.Image,
        startedAt: info.State.StartedAt,
        finishedAt: info.State.FinishedAt,
        restartCount: info.RestartCount,
        ports: info.NetworkSettings.Ports,
        config
      }
    } catch (err) {
      // Docker down or container doesn't exist — both are "not found"
      if (err.code === 'ENOENT' || err.code === 'ECONNREFUSED') {
        return { ...notFound, status: 'docker_unavailable' }
      }
      return notFound
    }
  }

  async start (overrides) {
    let config = this.loadConfig()
    if (overrides) config = deepMerge(config, overrides)

    const errs = validate(config)
    if (errs.length) {
      const err = new Error(`Invalid config: ${errs.join('; ')}`)
      err.statusCode = 400
      throw err
    }

    this.saveConfig(config)
    const { deployment: dep, translator: t } = config
    const image = `${dep.image}:${dep.imageTag}`

    // Pull image
    if (dep.pullPolicy === 'always') {
      await this._dockerCall(() => this._pull(image))
    } else if (dep.pullPolicy === 'ifNotPresent') {
      const exists = await this._dockerCall(() => this._imageExists(image))
      if (!exists) await this._dockerCall(() => this._pull(image))
    }

    // Write TOML config
    this._writeToml(t)

    // Remove old container
    const existing = await this._dockerCall(() => this._findContainer(dep.containerName))
    if (existing) {
      try { await existing.stop() } catch { /* already stopped */ }
      await existing.remove()
    }

    // Port bindings
    const dsPort = `${t.downstreamPort}/tcp`
    const monPort = parseMonitoringPort(t.monitoringAddress)
    const portBindings = { [dsPort]: [{ HostPort: String(dep.hostDownstreamPort) }] }
    const exposedPorts = { [dsPort]: {} }
    if (monPort) {
      const mp = `${monPort}/tcp`
      portBindings[mp] = [{ HostPort: String(dep.hostMonitoringPort) }]
      exposedPorts[mp] = {}
    }

    // Create and start
    const container = await this._dockerCall(() => this.docker.createContainer({
      Image: image,
      name: dep.containerName,
      ExposedPorts: exposedPorts,
      Entrypoint: ['/app/translator_sv2'],
      HostConfig: {
        Binds: [`${path.resolve(this.tomlFile)}:${CONTAINER_CONFIG_PATH}:ro`],
        PortBindings: portBindings,
        RestartPolicy: { Name: dep.restartPolicy }
      }
    }))
    await container.start()
    return this.getStatus()
  }

  async stop () {
    const config = this.loadConfig()
    const container = await this._dockerCall(() => this._findContainer(config.deployment.containerName))
    if (!container) {
      const err = new Error('Container not found')
      err.statusCode = 404
      throw err
    }
    const info = await container.inspect()
    if (!info.State.Running) {
      const err = new Error('Container is not running')
      err.statusCode = 409
      throw err
    }
    await container.stop({ t: 10 })
    return this.getStatus()
  }

  async getLogs (opts = {}) {
    const config = this.loadConfig()
    const container = await this._dockerCall(() => this._findContainer(config.deployment.containerName))
    if (!container) {
      const err = new Error('Container not found')
      err.statusCode = 404
      throw err
    }

    const logOpts = { stdout: true, stderr: true, follow: false, tail: opts.tail || 100 }
    if (opts.since) logOpts.since = opts.since

    const stream = await container.logs(logOpts)
    let buf
    if (Buffer.isBuffer(stream)) {
      buf = stream
    } else {
      buf = await new Promise((resolve, reject) => {
        const chunks = []
        stream.on('data', chunk => chunks.push(chunk))
        stream.on('end', () => resolve(Buffer.concat(chunks)))
        stream.on('error', reject)
      })
    }
    return demuxStream(buf)
  }
}

module.exports = { TranslatorSv2Service, DEFAULTS, deepMerge, generateToml, validate }
